name: sql_dataware_house_project
version: 1.0.0
profile: sql_dataware_house_project
config-version: 2

models:
  sql_dataware_house_project:

    staging:
      +schema: bronze        # camada inicial (raw)
      +materialized: view

    marts:
      +schema: silver        # camada analítica/modelada
      +materialized: table
